# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7fdbfc36-934f-4182-b3b0-96f41a217849";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/80AD-D214";
      fsType = "vfat";
    };

  fileSystems."/spool" =
    { device = "spool";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e8ade1e8-33c1-45c5-87e5-df0478a6292c"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
