#!/usr/bin/env bash

set -o errexit
set -o pipefail

nixev() {
  nix-instantiate --eval --strict -E "$1"
}

desc_system() {
  nixev '(import <nixpkgs> {}).stdenv.hostPlatform.system'
}

if [ "$#" -eq 0 ]; then
  echo "Fetching system info"
  sys="$(desc_system | jq -r)"
else
  sys="$1"
  shift
fi

linkdir="$(mktemp -d)"
link="$linkdir/result"

options=""
if [[ -z "$DISABLE_LOCAL_CACHE" ]]; then
  options="$options --option substituters https://cache.nixos.org"
fi

package="danielle_nogui"
hostname="$(hostname -s)"

if [[ "$hostname" = "sfyri" ]]; then
  package="danielle_gui"
fi

echo "Building $package home for: $sys"
nix build --extra-experimental-features "nix-command flakes" $options --out-link "$link" .#homeConfigurations.$sys.$package.activationPackage
path="$(readlink "$link")"
rm -rf "$linkdir"

exec "$path/activate"
