name: "Build System Configurations"
on:
  pull_request:
  push:
jobs:
  build-mir:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.mir.config.system.build.toplevel
    - run: nix flake check
